import {CompanyModel} from "../data-models/Company.model";

export var companyDataStore: CompanyModel[] = [
  {
    id: "1",
    name: "Facebook",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "loerm ipsum dolor sit amet consectetur adipiscing elit loerm ipsum dolor sit amet consectetur adipiscing elitloerm ipsum dolor sit amet consectetur adipiscing elitloerm ipsum dolor sit amet consectetur adipiscing elit \n lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.facebook.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  },
  {
    id: "2",
    name: "Google",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.google.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 12000,
    following: 150
  },
  {
    id: "3",
    name: "Apple",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.apple.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  },
  {
    id: "4",
    name: "Microsoft",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.microsoft.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  },
  {
    id: "5",
    name: "Amazon",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.amazon.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  },
  {
    id: "6",
    name: "Google",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.google.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  },
  {
    id: "7",
    name: "Apple",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.apple.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  },
  {
    id: "8",
    name: "Netflix",
    shortDescription: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyStory: "lorem ipsum dolor sit amet consectetur adipiscing elit lorem ipsum dolor sit amet consectetur adipiscing elit",
    companyLevel: "1",
    logo: "",
    location: "London, UK",
    profileBanner: "",
    image1: "",
    image2: "",
    image3: "",
    foundedDate: "2003-01-01",
    founderName: "Niklas Zennstroem",
    headquarters: "London",
    numberOfEmployees: "750",
    website: "https://www.netflix.com",
    linkedin: "https://www.linkedin.com",
    twitter: "https://www.twitter.com",
    facebook: "https://www.facebook.com",
    instagram: "https://www.instagram.com",
    youtube: "https://www.youtube.com",
    tiktok: "https://www.tiktok.com",
    contactEmail: "sHhjz@example.com",
    contactNumber: "0123456789",
    postedJobs: {},
    joinedDate: "Sat Sep 21 2024 07:42:48 GMT+0000",
    isVerified: "verified",
    followers: 10000,
    following: 230
  }
]
